default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: 5cbookshare
  password: <%= ENV['BOOKSHARE_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
